# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Workspace/Vivado_16.4/2017_10_17_FFT/Design/IP_Core/ADD/ADD/ADD.xci
# IP: The module: 'ADD' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Workspace/Vivado_16.4/2017_10_17_FFT/Design/IP_Core/ADD/ADD/ADD_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ADD'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: e:/Workspace/Vivado_16.4/2017_10_17_FFT/Design/IP_Core/ADD/ADD/ADD.xci
# IP: The module: 'ADD' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Workspace/Vivado_16.4/2017_10_17_FFT/Design/IP_Core/ADD/ADD/ADD_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ADD'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
