# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tftg256-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/Workspace/Vivado_16.4/2017_10_21_FFT/FFT.cache/wt [current_project]
set_property parent.project_path E:/Workspace/Vivado_16.4/2017_10_21_FFT/FFT.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/Workspace/Vivado_16.4/2017_10_21_FFT/FFT.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files E:/Workspace/Vivado_16.4/2017_10_21_FFT/Design/IP_Core/cos_14_1024_signed.coe
add_files -quiet e:/Workspace/Vivado_16.4/2017_10_21_FFT/Design/IP_Core/ROM/ROM/ROM.dcp
set_property used_in_implementation false [get_files e:/Workspace/Vivado_16.4/2017_10_21_FFT/Design/IP_Core/ROM/ROM/ROM.dcp]
add_files -quiet E:/Workspace/Vivado_16.4/2017_10_21_FFT/Design/IP_Core/FFT/FFT/FFT.dcp
set_property used_in_implementation false [get_files E:/Workspace/Vivado_16.4/2017_10_21_FFT/Design/IP_Core/FFT/FFT/FFT.dcp]
read_verilog -library xil_defaultlib {
  E:/Workspace/Vivado_16.4/2017_10_21_FFT/Design/Code/test_wave.v
  E:/Workspace/Vivado_16.4/2017_10_21_FFT/Design/Code/FFT_Control.v
  E:/Workspace/Vivado_16.4/2017_10_21_FFT/Design/Code/TOP.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top TOP -part xc7a35tftg256-1


write_checkpoint -force -noxdef TOP.dcp

catch { report_utilization -file TOP_utilization_synth.rpt -pb TOP_utilization_synth.pb }
